In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('Sonar_dataset.csv',header=None)
data.head(3)

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  

[3 rows x 61 columns]

In [3]:
data.shape

(208, 61)

In [4]:
data.isna().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [5]:
data[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [6]:
x = data.drop(60,axis=1)
y = data[60]

In [7]:
y = y.replace({'R':1,'M':0})

In [8]:
y.value_counts()

0    111
1     97
Name: 60, dtype: int64

In [9]:
# pd.get_dummies(y, drop_first= True)

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=.25,random_state=1)

In [11]:
x_train.shape,   x_test.shape

((156, 60), (52, 60))

In [12]:
y_train.shape,  y_test.shape

((156,), (52,))

In [13]:
import tensorflow as tf 
from tensorflow import keras

In [14]:
model= keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation='relu'),
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dense(1,  activation='sigmoid')
])

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(x_train,y_train,epochs=100,batch_size=8)

Epoch 1/100
20/20 [==============================] - 1s 1ms/step - loss: 0.6862 - accuracy: 0.5260
Epoch 2/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6477 - accuracy: 0.5819
Epoch 3/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6376 - accuracy: 0.6636
Epoch 4/100
20/20 [==============================] - 0s 1ms/step - loss: 0.6162 - accuracy: 0.6776
Epoch 5/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5940 - accuracy: 0.6648
Epoch 6/100
20/20 [==============================] - 0s 1ms/step - loss: 0.5521 - accuracy: 0.8375
Epoch 7/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4913 - accuracy: 0.8478
Epoch 8/100
20/20 [==============================] - 0s 1ms/step - loss: 0.4900 - accuracy: 0.7913
Epoch 9/100
20/20 [==============================] - 0s 1ms/step - loss: 0.4752 - accuracy: 0.7702
Epoch 10/100
20/20 [==============================] - 0s 1ms/step - loss: 0.4737 - accuracy: 0.8546
Epoch 11/

In [15]:
model.evaluate(x_test,y_test)

2/2 [==============================] - 0s 997us/step - loss: 1.3393 - accuracy: 0.7500


[1.3392977714538574, 0.75]

In [16]:
y_predict=model.predict(x_test)

In [17]:
y_predict.reshape(-1)

array([3.00906912e-12, 9.98283863e-01, 2.02378303e-01, 7.94052397e-08,
       9.99950409e-01, 9.97735083e-01, 5.40749431e-02, 9.99972939e-01,
       1.91851882e-07, 9.99963760e-01, 1.42899156e-03, 5.77019773e-06,
       5.12301922e-04, 2.10076571e-04, 1.22013688e-02, 3.73765528e-01,
       9.96338606e-01, 2.97826182e-06, 8.29368830e-04, 9.99647856e-01,
       3.22897336e-07, 9.99935091e-01, 9.38403606e-03, 9.99187648e-01,
       3.01695891e-05, 1.37732784e-10, 3.51307392e-02, 1.06436535e-04,
       9.99875784e-01, 1.21574685e-05, 9.77903366e-01, 6.22740137e-10,
       4.28103209e-01, 6.17057085e-04, 9.94741201e-01, 9.99541402e-01,
       9.99511003e-01, 3.61046135e-01, 9.99232411e-01, 7.17371702e-04,
       1.69235468e-03, 6.99967146e-04, 1.14208400e-01, 6.63166247e-07,
       2.69825563e-07, 1.38676442e-05, 1.37060285e-02, 9.99912381e-01,
       1.24728680e-03, 4.39319015e-03, 8.26358795e-02, 2.08113676e-07],
      dtype=float32)

In [18]:
y_predict  = np.round(y_predict)
y_predict.reshape(-1)

array([0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
       1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0.], dtype=float32)

In [19]:
y_predict.shape

(52, 1)

In [20]:
y_test[:5]

186    0
155    0
165    0
200    0
58     1
Name: 60, dtype: int64

In [21]:
from sklearn.metrics import confusion_matrix,classification_report

In [22]:
print(classification_report(y_test , y_predict))

              precision    recall  f1-score   support

           0       0.69      0.93      0.79        27
           1       0.88      0.56      0.68        25

    accuracy                           0.75        52
   macro avg       0.78      0.74      0.74        52
weighted avg       0.78      0.75      0.74        52



In [23]:
cm = confusion_matrix(y_test,y_predict)
cm

array([[25,  2],
       [11, 14]], dtype=int64)

In [29]:
model_d= keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation='relu'),
    keras.layers.Dropout(.5),
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dropout(.5),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dropout(.5),
    keras.layers.Dense(1,  activation='sigmoid')
])

model_d.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model_d.fit(x_train,y_train,epochs=100,batch_size=8)

Epoch 1/100
20/20 [==============================] - 0s 892us/step - loss: 0.7682 - accuracy: 0.4823
Epoch 2/100
20/20 [==============================] - 0s 1ms/step - loss: 0.7481 - accuracy: 0.3916
Epoch 3/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7011 - accuracy: 0.5449
Epoch 4/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7045 - accuracy: 0.4618
Epoch 5/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7119 - accuracy: 0.4669
Epoch 6/100
20/20 [==============================] - 0s 1ms/step - loss: 0.6548 - accuracy: 0.6017
Epoch 7/100
20/20 [==============================] - 0s 1ms/step - loss: 0.7038 - accuracy: 0.5457
Epoch 8/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6781 - accuracy: 0.5167
Epoch 9/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6795 - accuracy: 0.5290
Epoch 10/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6707 - accuracy: 0.5772
Epoch 1

In [28]:
model_d.evaluate(x_test,y_test)

2/2 [==============================] - 0s 2ms/step - loss: 0.4038 - accuracy: 0.8462


[0.4037635922431946, 0.8461538553237915]

In [30]:
y_predicted = model_d.predict(x_test)

In [31]:
y_predicted  = np.round(y_predicted)
y_predicted.reshape(-1)

array([0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1.,
       1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1.,
       0.], dtype=float32)

In [32]:
print(classification_report(y_test , y_predicted))

              precision    recall  f1-score   support

           0       0.73      0.81      0.77        27
           1       0.77      0.68      0.72        25

    accuracy                           0.75        52
   macro avg       0.75      0.75      0.75        52
weighted avg       0.75      0.75      0.75        52

